server:
  port: 9000
  servlet:
    context-path: "/api/v1"

cs-central:
  root-db-name: "csc-root"
  user-db-prefix: "csc-user-db-"
  admin-username: ${CENTRAL_ADMIN_USERNAME}
  admin-password: ${CENTRAL_ADMIN_PASSWORD}

couchdb:
  url: ${COUCH_DB_URI}
  username: ${COUCH_DB_ADMIN_USERNAME}
  password: ${COUCH_DB_ADMIN_PASSWORD}


logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
